### PR TITLE
fix: Add the file into the folder.

### PR DESCRIPTION
**Pull request by lsy109**
**Description**
See #1

### CODE REVIEW

**Review by ping-yee — APPROVED** [review]
LGTM!

**Comment by ping-yee** [comment]
You should add the action type into the title to be the prefix next time, like `fix:` `enhance:`.

**Comment by lsy109** [comment]
Is it changed to this?

**Comment by ping-yee** [comment]
I have modified the title befroe but I forgot to merged, Sor.

**Pull request merged**
