### PR TITLE
fix: Add the file into the folder 

### PR DESCRIPTION
**Pull request by asakeaoyama**
Description :
See #1

### CODE REVIEW

**Comment by ping-yee** [comment]
Hi, You should follow the format to moidify the conversation description and title of this PR and mention the issue number.

**Comment by asakeaoyama** [comment]
Sorry for not following the specific format. I just modified the title of this PR to the title of the issue. Also the number of the issue '#1' is written on the rare. Please check it out and please don't hesitate to give me any responses or recommends. Thx!

**Comment by ping-yee** [comment]
First, You can refer the other PRs that have been mentioned the issue number format to modify (e.g. #5).
Second, I don't think that the action of mention issue number is rare because there are most open source projects are using this operation.

**Comment by asakeaoyama** [comment]
Thanks for the reply. I sincerely apologize for the misconceptions. I've modified the title of my PR title by referring the others and here is my description below!

Description :
See #1 

If there is still any thing not very well, please let me know. Good day!

**Comment by ping-yee** [comment]
LGTM

**Pull request merged**
